spring.application.name=kpi

oracle.wallet.path=/home/sammy/Desktop/PROJECT/Backend/taskbot-backend/kpi-service/src/main/resources/Wallet

# 1. Conexi�n a la Base de Datos usando la Wallet
# spring.datasource.url=jdbc:oracle:thin:@botbd_tp?TNS_ADMIN=classpath:Wallet
spring.datasource.url=jdbc:oracle:thin:@botbd_tp?TNS_ADMIN=${oracle.wallet.path}

# 2. credenciales de Oracle Cloud
spring.datasource.username=CREDENTIALS
spring.datasource.password=CREDENTIALS

# 3. Configuraci�n del Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Configuraci�n de Hibernate (Evita que te borre tus tablas actuales)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
