spring.application.name=kpi

# Solo se modifica oracle.wallet.path y las credenciales

# La ruta se cambia por la ruta absoluta (completa) de donde se tienen todos los archivos que nos da OCI. En este caso esta dentro de resources en el proyecto.
oracle.wallet.path=/app/Wallet

# 1. Conexi�n a la Base de Datos usando la Wallet
# spring.datasource.url=jdbc:oracle:thin:@botbd_tp?TNS_ADMIN=classpath:Wallet
spring.datasource.url=jdbc:oracle:thin:@botbd_tp?TNS_ADMIN=${oracle.wallet.path}

# 2. credenciales de Oracle Cloud
spring.datasource.username=USER
spring.datasource.password=PASSWORD

# 3. Configuraci�n del Driver
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Configuraci�n de hibernate (Evita que se borren las tablas actuales)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

# Kafka Consumer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=web-workers-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# JWT Security Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

springdoc.swagger-ui.url=/v3/api-docs/kpis
