spring.application.name=telegram

feign.client.config.kpi-service.url=${KPI_SERVICE_URL:http://kpi-service:8080}

telegram.bot.token=${TELEGRAM_BOT_TOKEN}

server.port=8081

auth.service.url=${AUTH_SERVICE_URL:http://auth-service:8082}
