server.port=8083
spring.application.name=ai-service

logging.level.dev.sammy_ulfh.ai=DEBUG

openai.api.key=${OPENAI_API_KEY}

oracle.wallet.path=${ORACLE_WALLET_PATH:/app/Wallet}

spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${ORACLE_WALLET_PATH:/app/Wallet}
spring.datasource.hikari.data-source-properties.TNS_ADMIN=${ORACLE_WALLET_PATH:/app/Wallet}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

springdoc.swagger-ui.url=/v3/api-docs/ia
server.servlet.context-path=/
