server.port=8083
spring.application.name=ai-service

logging.level.dev.sammy_ulfh.ai=DEBUG

openai.api.key=${OPENAI_API_KEY}

# Wallet
oracle.wallet.path=${ORACLE_WALLET_PATH:/app/Wallet}

# Oracle DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${TNS_ADMIN:/app/Wallet}
spring.datasource.hikari.data-source-properties.TNS_ADMIN=${TNS_ADMIN:/app/Wallet}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

springdoc.swagger-ui.url=/v3/api-docs/ia
