server.port=8083
spring.application.name=ai-service

logging.level.dev.sammy_ulfh.ai=DEBUG

# Wallet
oracle.wallet.path=${ORACLE_WALLET_PATH:/Users/diana/Documents/TECNOLOGICO DE MONTERREY/SEXTO SEMESTRE/Backend/taskbot-backend/ai-service/src/main/resources/Wallet}

# Oracle DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@gestiondetareasbd_tp}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:CHATBOT_USER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Chatbot2026AB}
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${TNS_ADMIN:/Users/diana/Documents/TECNOLOGICO DE MONTERREY/SEXTO SEMESTRE/Backend/taskbot-backend/ai-service/src/main/resources/Wallet}
spring.datasource.hikari.data-source-properties.TNS_ADMIN=${TNS_ADMIN:/Users/diana/Documents/TECNOLOGICO DE MONTERREY/SEXTO SEMESTRE/Backend/taskbot-backend/ai-service/src/main/resources/Wallet}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

springdoc.swagger-ui.url=/v3/api-docs/ia
server.servlet.context-path=/


# Gemini API Configuration
gemini.api.key=AIzaSyCHYXc06IClVbVtiUVLMkjk0pD2XxL5ST8
gemini.api.model=gemini-2.5-flash
gemini.api.url=https://generativelanguage.googleapis.com/v1/models/${gemini.api.model}:generateContent?key=${gemini.api.key}
gemini.embedding.url=https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:embedContent?key=${gemini.api.key}
gemini.max-output-tokens=1024
gemini.temperature=0.7

